from simple_ddl_parser import DDLParser


def test_inherits():
    ddl = """
    CREATE TABLE public."Diagnosis_identifier" (
        "Diagnosis_id" text NOT NULL
    )
    INHERITS (public.identifier);
    """

    result = DDLParser(ddl).run(output_mode="postgres")

    expected = [
        {
            "alter": {},
            "checks": [],
            "columns": [
                {
                    "check": None,
                    "default": None,
                    "name": '"Diagnosis_id"',
                    "nullable": False,
                    "references": None,
                    "size": None,
                    "type": "text",
                    "unique": False,
                }
            ],
            "index": [],
            "inherits": {"schema": "public", "table_name": "identifier"},
            "partitioned_by": [],
            "primary_key": [],
            "schema": "public",
            "table_name": '"Diagnosis_identifier"',
            "tablespace": None,
        }
    ]
    assert expected == result


def test_cast_generated():
    ddl = """CREATE TABLE test (
      timestamp TIMESTAMP,
      date DATE GENERATED ALWAYS AS (CAST(timestamp AS DATE))
    )"""

    result = DDLParser(ddl).run(output_mode="postgres")
    expected = [
        {
            "alter": {},
            "checks": [],
            "columns": [
                {
                    "check": None,
                    "default": None,
                    "name": "timestamp",
                    "nullable": True,
                    "references": None,
                    "size": None,
                    "type": "TIMESTAMP",
                    "unique": False,
                },
                {
                    "check": None,
                    "default": None,
                    "generated": {
                        "always": True,
                        "as": {"cast": {"as": "DATE", "value": "timestamp"}},
                        "stored": False,
                    },
                    "name": "date",
                    "nullable": True,
                    "references": None,
                    "size": None,
                    "type": "DATE",
                    "unique": False,
                },
            ],
            "index": [],
            "partitioned_by": [],
            "primary_key": [],
            "schema": None,
            "table_name": "test",
            "tablespace": None,
        }
    ]
    assert expected == result


def test_with_time_zone():
    expected = [
        {
            "alter": {},
            "checks": [],
            "columns": [
                {
                    "check": None,
                    "default": None,
                    "name": "date_updated",
                    "nullable": True,
                    "references": None,
                    "size": None,
                    "type": "timestamp",
                    "unique": False,
                    "with_time_zone": True,
                }
            ],
            "index": [],
            "partitioned_by": [],
            "primary_key": [],
            "schema": "public",
            "table_name": "test",
            "tablespace": None,
        }
    ]
    ddl = """
    CREATE TABLE public.test (date_updated timestamp with time zone);"""

    result = DDLParser(ddl).run(output_mode="postgres")
    assert expected == result


def test_generated_by_default_identity_with_check_constraint():
    ddl = """
    CREATE TABLE pole.t_zuschauer (
        id int4 GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE
        ) NOT NULL,
        email varchar(50) NULL,
        CONSTRAINT t_zuschauer_email CHECK (
            ((email IS NULL)
            OR ((email)::text = ''::text)
            OR ((email)::text ~* '([a-zA-Z0-9._%+-]+)@([a-zA-Z0-9.-]+)\\.[a-zA-Z]{2,}'::text))
        ),
        CONSTRAINT t_zuschauer_id PRIMARY KEY (id)
    );
    """

    result = DDLParser(ddl).run(output_mode="postgres")

    assert len(result) == 1
    assert result[0]["schema"] == "pole"
    assert result[0]["table_name"] == "t_zuschauer"
    assert result[0]["primary_key"] == ["id"]
    assert result[0]["columns"][0]["generated_by"] == (
        "DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 "
        "START 1 CACHE 1 NO CYCLE)"
    )
    assert result[0]["checks"][0]["constraint_name"] == "t_zuschauer_email"
    assert "email IS NULL" in result[0]["checks"][0]["statement"]


def test_generated_always_identity_with_options_issue_257():
    ddl = """
    CREATE TABLE IF NOT EXISTS public.generator_id (
        hall_id int4 GENERATED ALWAYS AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE
        ) NOT NULL,
        hall_name varchar(50) NOT NULL,
        CONSTRAINT hall_pkey PRIMARY KEY (hall_id)
    );
    """

    result = DDLParser(ddl).run(output_mode="postgres")

    assert len(result) == 1
    assert result[0]["schema"] == "public"
    assert result[0]["table_name"] == "generator_id"
    assert result[0]["primary_key"] == ["hall_id"]
    assert result[0]["columns"][0]["generated_by"] == (
        "ALWAYS AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 "
        "START 1 CACHE 1 NO CYCLE)"
    )
    assert result[0]["columns"][0]["nullable"] is False
    assert result[0]["columns"][1]["name"] == "hall_name"
